[project]
name = "real-temperature-proxy-api"
version = "0.1.0"
description = "Real Temperature Proxy API normalizing results fetched from Open-Meteo "
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[uvicorn]>=0.128.0",
]
